defaults: &defaults
  secret_key_base:  cedabf53a2908b544ae9829d670665ca6635f503dcbc8fabb1e57e43a3f97b67eb477956832ed6f6031cac60f57c45c8ad95d30c6f2d6f65a420d23d4764dfd0
  username: root
  password: s1bul111
  hostname: localhost

production:
  <<: *defaults
  database: bapas_production

development:
  <<: *defaults
  database: bapas_development

test:
  <<: *defaults
  database: bapas_test
