source 'https://rubygems.org'

gem 'rails', '4.2.1'
platform :jruby do
  gem 'activerecord-jdbcmysql-adapter'
end

platform :ruby do
  gem 'mysql2'
end
gem 'jbuilder'
gem 'awesome_nested_set'
gem 'kaminari'

gem "activeadmin", github: "gregbell/active_admin"
gem "devise"
gem "active_model_serializers"
gem "rack-cors", require: "rack/cors"

gem 'jquery-rails'
gem 'uglifier'

group :test do
  gem 'rake'
  gem 'minitest'
end
